/**
 * @fileoverview Script to fetch and generate Register.sol with CCIP network details from Chainlink's API.
 * 
 * This script queries Chainlink's CCIP API endpoints to retrieve network configuration
 * details for all supported EVM chains. It fetches chain information (routers, selectors,
 * fee tokens) and token information (CCIP-BnM and CCIP-LnM addresses) for both testnet
 * and mainnet environments, then generates:
 *   - `src/ccip/RegisterData.sol`: one data shard contract per SHARD_SIZE chains, with readable
 *     per-chain tables, plus a helper that places the shards with `vm.etch`;
 *   - the shard count constant in the generated region of `src/ccip/Register.sol`.
 *
 * The data lives in code rather than in constructor-initialised storage: writing ~150 chains to
 * storage cost ~24M gas, which made `new CCIPLocalSimulatorFork()` exceed the block gas limit of
 * 30M-gas forks. Sharding keeps every contract runtime under the EIP-170 limit, so downstream
 * projects that size-gate compiled artifacts can consume the package.
 * 
 * Usage:
 *    CCIP_API_BASE_URL=<base_url> npm run update-register
 *    CCIP_API_BASE_URL=<base_url> node helper_doc/updateRegisterContract.cjs
 *
 * Requires: CCIP_API_BASE_URL environment variable (base URL for the CCIP API; paths are appended in code), e.g.
 * https://docs.chain.link/api/ccip/v1 (the CCIP directory API; https://api.ccip.chain.link/v2 has no routers or fee tokens).
 *
 */

const fs = require("fs");
const path = require("path");

/**
 * Normalized base URL (no trailing slash) for building API requests.
 * @returns {string} Base URL from the CCIP_API_BASE_URL environment variable
 */
function getApiBase() {
  const base = process.env.CCIP_API_BASE_URL;
  if (!base || base.trim() === "") {
    console.error("Error: CCIP_API_BASE_URL environment variable is required and must be set.");
    process.exit(1);
  }
  return base.trim().replace(/\/$/, "");
}

/**
 * Builds the full API URL for a given path and query parameters.
 * @param {string} path - Path segment (e.g. "chains", "tokens")
 * @param {Record<string, string>} params - Query parameters
 * @returns {string} Full URL
 */
function apiUrl(path, params) {
  const url = new URL(`${getApiBase()}/${path}`);
  Object.entries(params).forEach(([k, v]) => url.searchParams.set(k, v));
  return url.toString();
}

/** Marker lines delimiting the generated shard count in Register.sol. */
const GENERATED_BEGIN = "    // <generated-network-details> Generated by helper_doc/updateRegisterContract.cjs. Do not edit by hand.";
const GENERATED_END = "    // </generated-network-details>";

/** Maximum number of chains packed into one generated `RegisterDataN` contract. */
const SHARD_SIZE = 40;

/** Address fields of `Register.NetworkDetails`, in table order. */
const ADDRESS_FIELDS = [
    "routerAddress",
    "linkAddress",
    "wrappedNativeAddress",
    "ccipBnMAddress",
    "ccipLnMAddress",
    "rmnProxyAddress",
    "registryModuleOwnerCustomAddress",
    "tokenAdminRegistryAddress"
];

/**
 * Splits the network details into shards of at most SHARD_SIZE chains, sorted by chain id.
 *
 * @param {Object} networkDetails - Network details keyed by chain ID
 * @returns {string[][]} Chain ID lists, one per shard
 */
function buildShards(networkDetails) {
    const chainIds = Object.keys(networkDetails).sort((a, b) => Number(a) - Number(b));
    const shards = [];
    for (let i = 0; i < chainIds.length; i += SHARD_SIZE) shards.push(chainIds.slice(i, i + SHARD_SIZE));
    return shards;
}

const addressLiteral = (value) => (!value || /^0x0{40}$/i.test(value) ? "address(0)" : `address(${value})`);

/**
 * Formats one chain entry of a shard's lookup function.
 *
 * @param {string} chainId - The chain ID
 * @param {Object} details - The chain's network details
 * @returns {string} Solidity source for the entry
 */
function formatEntry(chainId, details) {
    const name = details.name || `Chain ${chainId}`;

    let entry = `        // ${name}\n`;
    entry += `        if (chainId == ${chainId}) {\n`;
    entry += "            return (\n";
    entry += "                Register.NetworkDetails({\n";
    entry += `                    chainSelector: ${details.chainSelector},\n`;
    ADDRESS_FIELDS.forEach((field, index) => {
        const comma = index === ADDRESS_FIELDS.length - 1 ? "" : ",";
        entry += `                    ${field}: ${addressLiteral(details[field])}${comma}\n`;
    });
    entry += "                }),\n";
    entry += "                true\n";
    entry += "            );\n";
    entry += "        }\n";
    return entry;
}

/**
 * Builds the generated RegisterData.sol contents: one data shard contract per SHARD_SIZE chains, plus a
 * helper library that places the shards with `vm.etch` at the addresses `Register.shardAddress` returns.
 *
 * @param {Object} networkDetails - Network details keyed by chain ID
 * @returns {string} Solidity source for RegisterData.sol
 */
function formatRegisterData(networkDetails) {
    const shards = buildShards(networkDetails);

    let out = "";
    out += "// SPDX-License-Identifier: BUSL-1.1\n";
    out += "pragma solidity ^0.8.0;\n\n";
    out += "// Generated by helper_doc/updateRegisterContract.cjs. Do not edit by hand.\n\n";
    out += 'import {Vm} from "forge-std/Vm.sol";\n';
    out += 'import {Register} from "./Register.sol";\n\n';

    shards.forEach((chainIds, index) => {
        out += `/// @dev Built-in network details for ${chainIds.length} chains, decoded by Register._defaultNetworkDetails.\n`;
        out += `contract RegisterData${index} {\n`;
        out += "    /// @notice Built-in network details for `chainId`, or `(all-zero struct, false)` when not in this shard.\n";
        out += "    function get(uint256 chainId) external pure returns (Register.NetworkDetails memory details, bool found) {\n";
        for (const chainId of chainIds) out += formatEntry(chainId, networkDetails[chainId]);
        out += "        Register.NetworkDetails memory unknown;\n";
        out += "        return (unknown, false);\n";
        out += "    }\n";
        out += "}\n\n";
    });

    out += "/// @dev Places the generated data shards with `vm.etch` next to a `Register` instance.\n";
    out += "library RegisterDataShards {\n";
    out += "    function etchAll(Vm vm, address registerAddress) internal {\n";
    shards.forEach((_, index) => {
        out += `        address shard${index} = Register(registerAddress).shardAddress(${index});\n`;
        out += `        vm.etch(shard${index}, type(RegisterData${index}).runtimeCode);\n`;
        out += `        vm.makePersistent(shard${index});\n`;
    });
    out += "    }\n";
    out += "}\n";
    return out;
}

/**
 * Builds the generated region of Register.sol: the shard count constant.
 *
 * @param {Object} networkDetails - Network details keyed by chain ID
 * @returns {string} Solidity source for the generated region
 */
function formatRegisterMarkers(networkDetails) {
    const shards = buildShards(networkDetails);

    let body = "";
    body += "    /// @dev Number of generated data shards in RegisterData.sol.\n";
    body += `    uint256 internal constant _SHARD_COUNT = ${shards.length};\n`;
    return body;
}

/**
 * Generates the network details lookup of Register.sol.
 * The details are returned by a pure function, so they live in code and cost no gas to "deploy" when the
 * contract is placed with `vm.etch`, and are compatible with Hardhat and Remix (no Foundry cheatcodes or JSON reading).
 *
 * @param {string} outputPath - Path to output Register.sol. Defaults to src/ccip/Register.sol
 * @param {Object} networkDetails - Network details object to generate from.
 */
function generateRegister(outputPath, networkDetails) {
    // Default output path
    const defaultOutputPath = path.join(__dirname, "../src/ccip/Register.sol");
    const outputFilePath = outputPath || defaultOutputPath;

    const networkCount = Object.keys(networkDetails).length;

    // Write the generated data shards
    const registerDataPath = path.join(__dirname, "../src/ccip/RegisterData.sol");
    console.log(`Writing generated data shards to: ${registerDataPath}`);
    fs.writeFileSync(registerDataPath, formatRegisterData(networkDetails), "utf8");

    // Read the Register.sol file and replace the generated region between the markers
    const registerPath = path.join(__dirname, "../src/ccip/Register.sol");
    const registerCode = fs.readFileSync(registerPath, "utf8");
    const begin = registerCode.indexOf(GENERATED_BEGIN);
    const end = registerCode.indexOf(GENERATED_END);
    if (begin === -1 || end === -1 || end < begin) {
        throw new Error(`Could not find the generated region in Register.sol (expected the lines:\n${GENERATED_BEGIN}\n${GENERATED_END})`);
    }
    const generated =
        registerCode.slice(0, begin) + GENERATED_BEGIN + "\n" + formatRegisterMarkers(networkDetails) + registerCode.slice(end);

    // Write the generated file
    console.log(`Writing generated Register.sol to: ${outputFilePath}`);
    fs.writeFileSync(outputFilePath, generated, "utf8");

    console.log(`  Successfully generated Register.sol and RegisterData.sol with ${networkCount} networks`);
    console.log(`  Output: ${outputFilePath}`);
}

/**
 * Picks the wrapped native token from a chain's fee tokens. The API does not mark it, and lists fee tokens in no fixed
 * order (e.g. GHO before WETH), so the first non-LINK fee token is not reliable.
 * Rule: the only W-prefixed fee token; if there are several, the only one that is not WETH (a bridged WETH next to
 * the chain's own wrapped native token, e.g. WMON on Monad Testnet).
 *
 * @param {Array<{symbol: string, address: string}>} feeTokens - The chain's fee tokens
 * @returns {?{symbol: string, address: string}} The wrapped native token, or null when missing or ambiguous
 */
function selectWrappedNativeToken(feeTokens) {
  const wrapped = (feeTokens || []).filter((token) => token.symbol.startsWith("W"));
  if (wrapped.length === 1) return wrapped[0];
  const notWETH = wrapped.filter((token) => token.symbol !== "WETH");
  return notWETH.length === 1 ? notWETH[0] : null;
}

/**
 * Fetches CCIP network details for a single environment from Chainlink's API.
 * 
 * @param {string} environment - The environment to fetch data for ("testnet" or "mainnet")
 * @returns {Promise<Object>} Network details object keyed by chain ID
 */
async function fetchNetworkDetails(environment) {
  const queryBase = { environment, outputKey: "chainId" };

  // Call Endpoint #1: chains
  const chainsRes = await fetch(apiUrl("chains", { ...queryBase, enrichFeeTokens: "true" }), {
    headers: { Accept: "application/json" }
  });
  if (!chainsRes.ok) {
    const body = await chainsRes.text();
    throw new Error(`Chains API HTTP ${chainsRes.status} ${chainsRes.statusText} for ${environment}\n${body}`);
  }
  const chainsData = await chainsRes.json();

  // Call Endpoint #2: tokens
  const tokensRes = await fetch(apiUrl("tokens", queryBase), {
    headers: { Accept: "application/json" }
  });
  if (!tokensRes.ok) {
    const body = await tokensRes.text();
    throw new Error(`Tokens API HTTP ${tokensRes.status} ${tokensRes.statusText} for ${environment}\n${body}`);
  }
  const tokensData = await tokensRes.json();

  // Process the data
  const networkDetails = {};
  const evmChains = chainsData.data.evm || {};
  const ccipBnM = tokensData.data["CCIP-BnM"] || {};
  const ccipLnM = tokensData.data["CCIP-LnM"] || {};

  // Iterate through all EVM chains
  for (const [chainId, chainInfo] of Object.entries(evmChains)) {
    // Find LINK token and wrapped native token from feeTokens
    const linkToken = chainInfo.feeTokens?.find(token => token.symbol === "LINK");
    const hasOtherFeeToken = chainInfo.feeTokens?.some(token => token.symbol !== "LINK");
    const wrappedNativeToken = selectWrappedNativeToken(chainInfo.feeTokens);

    // Get CCIP token addresses from tokens endpoint
    const bnMInfo = ccipBnM[chainId];
    const lnMInfo = ccipLnM[chainId];

    // Only include chains that have all required data
    if (linkToken && hasOtherFeeToken && chainInfo.router && chainInfo.rmn &&
        chainInfo.registryModule && chainInfo.tokenAdminRegistry) {
      if (!wrappedNativeToken) {
        const symbols = chainInfo.feeTokens.map(token => token.symbol).join(", ");
        console.warn(`  Warning: ${chainInfo.displayName} (${chainId}): no unambiguous wrapped native fee token (${symbols}), using address(0)`);
      }
      networkDetails[chainId] = {
        name: chainInfo.displayName,
        chainSelector: chainInfo.selector,
        routerAddress: chainInfo.router,
        linkAddress: linkToken.address,
        wrappedNativeAddress: wrappedNativeToken?.address || "",
        ccipBnMAddress: bnMInfo?.tokenAddress || "",
        ccipLnMAddress: lnMInfo?.tokenAddress || "",
        rmnProxyAddress: chainInfo.rmn,
        registryModuleOwnerCustomAddress: chainInfo.registryModule,
        tokenAdminRegistryAddress: chainInfo.tokenAdminRegistry
      };
    }
  }

  return networkDetails;
}

/**
 * Fetches CCIP network details from Chainlink's API and generates Register.sol with hardcoded values.
 * Always fetches both testnet and mainnet network details.
 */
async function fetchAndGenerate() {
  try {
    let networkDetails = {};
    const environments = ["testnet", "mainnet"];

    // Fetch data for both environments in parallel
    console.log(`Fetching network details for: ${environments.join(", ")}...`);
    const fetchPromises = environments.map(env => fetchNetworkDetails(env));
    const results = await Promise.all(fetchPromises);

    // Merge network details from both environments
    // If there are duplicate chain IDs, mainnet takes precedence
    for (let i = 0; i < environments.length; i++) {
      const env = environments[i];
      const details = results[i];
      const envCount = Object.keys(details).length;
      console.log(`  ${env}: ${envCount} networks`);
      
      // Merge details, with later environments (mainnet) taking precedence
      for (const [chainId, chainDetails] of Object.entries(details)) {
        networkDetails[chainId] = chainDetails;
      }
    }

    // Generate Register.sol directly from API data
    const totalNetworks = Object.keys(networkDetails).length;
    console.log(`\nGenerating Register.sol with ${totalNetworks} total networks...`);
    generateRegister(null, networkDetails);
    
    console.log("\n  Register.sol generated successfully!");
  } catch (err) {
    console.error("Error:", err.message);
    process.exit(1);
  }
}

if (require.main === module) {
  require("dotenv").config();
  fetchAndGenerate();
}

module.exports = {
    generateRegister,
    buildShards,
    formatRegisterData,
    formatRegisterMarkers,
    selectWrappedNativeToken,
    fetchAndGenerate
};
