// SPDX-License-Identifier: BUSL-1.1
pragma solidity ^0.8.0;

/// @title Register Contract
/// @notice This contract allows storing and retrieving network details for various chains.
/// @dev Built-in network details live in the generated data shards of `RegisterData.sol` (see
///      `helper_doc/updateRegisterContract.cjs`), which the simulator places with `vm.etch`, instead of being
///      written to storage in the constructor: storing ~150 chains cost ~24M gas, which made
///      `CCIPLocalSimulatorFork` too expensive to deploy on 30M-gas-limit forks. Sharding keeps every
///      generated contract runtime under the EIP-170 limit. `setNetworkDetails` overrides are stored.
contract Register {
    struct NetworkDetails {
        uint64 chainSelector;
        address routerAddress;
        address linkAddress;
        address wrappedNativeAddress;
        address ccipBnMAddress;
        address ccipLnMAddress;
        address rmnProxyAddress;
        address registryModuleOwnerCustomAddress;
        address tokenAdminRegistryAddress;
    }

    /// @notice Network details set with `setNetworkDetails`, overriding the built-in ones.
    mapping(uint256 chainId => NetworkDetails) internal s_networkDetails;

    /// @notice Whether `setNetworkDetails` was called for a chain ID.
    mapping(uint256 chainId => bool isOverridden) internal s_isOverridden;

    /**
     * @notice Retrieves network details for a given chain ID.
     *
     * @param chainId - The ID of the chain to get the details for.
     * @return networkDetails - The network details for the specified chain ID.
     */
    function getNetworkDetails(uint256 chainId) external view returns (NetworkDetails memory networkDetails) {
        if (s_isOverridden[chainId]) {
            return s_networkDetails[chainId];
        }
        return _defaultNetworkDetails(chainId);
    }

    /**
     * @notice Sets the network details for a given chain ID.
     *
     * @param chainId - The ID of the chain to set the details for.
     * @param networkDetails - The network details to set for the specified chain ID.
     */
    function setNetworkDetails(uint256 chainId, NetworkDetails memory networkDetails) external {
        s_networkDetails[chainId] = networkDetails;
        s_isOverridden[chainId] = true;
    }

    // <generated-network-details> Generated by helper_doc/updateRegisterContract.cjs. Do not edit by hand.
    /// @dev Number of generated data shards in RegisterData.sol.
    uint256 internal constant _SHARD_COUNT = 4;

    // </generated-network-details>

    /// @notice Deterministic address of built-in data shard `index`; the simulator places each shard there.
    function shardAddress(uint256 index) public view returns (address) {
        return address(uint160(uint256(keccak256(abi.encode("chainlink-local.RegisterData", index, address(this))))));
    }

    /// @notice Built-in network details for `chainId`, or an all-zero struct for an unknown chain.
    /// @dev Decodes the generated data shards; shard addresses without code are skipped, so a bare
    ///      `new Register()` (no shards placed) only serves `setNetworkDetails` overrides.
    function _defaultNetworkDetails(uint256 chainId) internal view returns (NetworkDetails memory) {
        for (uint256 i = 0; i < _SHARD_COUNT; ++i) {
            (bool ok, bytes memory data) = shardAddress(i).staticcall(abi.encodeCall(IRegisterDataShard.get, (chainId)));
            if (ok && data.length != 0) {
                (NetworkDetails memory details, bool found) = abi.decode(data, (NetworkDetails, bool));
                if (found) return details;
            }
        }
        NetworkDetails memory unknown;
        return unknown;
    }
}

/// @dev Interface of the generated `RegisterDataN` shards.
interface IRegisterDataShard {
    function get(uint256 chainId) external pure returns (Register.NetworkDetails memory details, bool found);
}
